### ISSUE TITLE
在windows下运行无法生成测试报告？

### ISSUE THREAD

**Issue by eastchenyd** [SeldomQA/seldom#10]
![image](https://user-images.githubusercontent.com/34271012/33669090-7b6743ca-dadc-11e7-891c-633973b1e3d7.png)

![image](https://user-images.githubusercontent.com/34271012/33669153-9ef68a08-dadc-11e7-8260-560a1b4f80bb.png)

虫师，我在windows下正常运行，没有报错，怎么没有生成测试报告？截图红色框是我改动的地方，其他的没有改动。

**Comment by defnngj** [comment]
1.  请先执行安装：
```
pyse> python setup.py install
```
2、 不要直接运行（或修改）我的pyse 项目里的代码。 不是有demo/ 目录下的例子给你运行么？ 

3、搞不明名 pycharm 配置单元测试框架，就直接在window 命令提示符（或linux 终端）下执行。
```
demo> python test_case.py  
```

**Comment by defnngj** [comment]
第一张截图先把我的运行器给改了，我封装的是框架 ，又不是项目；你安装完一个框架，第一件事不是跑它的demo , 而是去修改 这个框架本身的代码么？  不满足这个框架自己去封装。或者自己熟悉这个框架的实现再去修改。

**Comment by 13410007989** [comment]
知道了，“运行脚本”与“运行单元测试”是不一样的，已配置pycharm 单元测试框架，解决在pycharm运行的问题，谢谢啊！

**Comment by empiregeneral** [comment]
怎么样在pycharm配置后能输出测试报告，能详细说明一下吗？
