### ISSUE TITLE
能否根据返回的json自动生成JsonSchema模板？

### ISSUE THREAD

**Issue by Kevin-liutianping** [SeldomQA/seldom#100]
描述：因为在做接口自动化对返回的json进行JsonSchema校验时，都需要去[https://www.jsonschema.net](https://www.jsonschema.net/home)手动复制生成的jsonschema模板，感觉有点不方便。我看到python中是存在生成模板的第三方库----[GenSON](https://github.com/wolverdude/GenSON)，感觉可以集成进来

**Comment by defnngj** [comment]
非常感谢你的建议，`version 2.9.0` 版本已经集成 genSON。 https://seldomqa.github.io/http/http.html#%E6%8F%90%E5%8F%96%E6%8E%A5%E5%8F%A3%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE

**Comment by Kevin-liutianping** [comment]
赞一个！！
