### ISSUE TITLE
纯好奇问下，为啥没用pytest？

### ISSUE THREAD

**Issue by Gary-CHAO1** [SeldomQA/seldom#104]

**Comment by nickliya** [comment]
纯好奇追问，为啥要用pytest？

**Comment by Gary-CHAO1** [comment]
> 纯好奇追问，为啥要用pytest？

不都说pytest好用么

**Comment by defnngj** [comment]
感兴趣看 seldom 公开课视频，我已经做了详细的解释。https://www.bilibili.com/video/BV1x5411U7tw
