### ISSUE TITLE
目前log日志记录的file不准确，只能输出file为log.py

### ISSUE THREAD

**Issue by footmanqq** [SeldomQA/seldom#107]
log重构后，用Logger包裹后，影响log输出的file的值不符合预期
seldom版本：2.9.0

如下
[ 2022-05-12 14:25:14 log.py | INFO | -------------- Response ----------------[🛬️]
[ 2022-05-12 14:25:14 log.py | INFO | successful with status 200 

日志内容输出格式：self._log_format = "[{time: YYYY-MM-DD HH:mm:ss} {file} | {level} | {message}"
{file}不符合实际期望的预期，希望{file}输出当前调用记录日志的文件， 而不是log.py这个文件

**Comment by yongchin0821** [comment]
可以查看[更新手册](https://github.com/SeldomQA/seldom/blob/master/CHANGES.md)
### 2.9.0
#### seldom log功能：
- 开放seldom 的log能力，可以配置颜色（colorlog）、格式(format)、等级(level) 等。
- 重新定义了seldom打印日志的格式。
- **所有log统一记录到/reports/seldom_log.log文件，不再每次生成单独文件。**

**Comment by yongchin0821** [comment]
> 

够呛，因为是在初始化的时候对Logger()进行实例化，所以打印出了log.py。

如果希望{file}输出当前调用记录日志的文件，需要重新实例化Logger()

这可能Logger()类实现方式或者初始化机制有关，后续会尝试优化

**Comment by defnngj** [comment]
可以使用：
```py
from seldom.logging.log import logger

logger.error("hello error")
```

日志
```
2022-05-13 14:42:44 xxx.py | ERROR | hello error
```

`xxx.py` 可以显示具体打印的文件名

缺点：

这些打印无法记录到 HTML报告中。

我 和 @yongchin0821  沟通了一下，还没找到有效的兼顾办法。

**Comment by defnngj** [comment]
@footmanqq  `seldom 2.10.0` 已彻底修复了这个问题。我们费了很大力气。这里特别感谢 @yongchin0821  ，他提供了解决方法。
