### ISSUE TITLE
子目录的用例不执行

### ISSUE THREAD

**Issue by cwk0099** [SeldomQA/seldom#110]
![image](https://user-images.githubusercontent.com/37758451/170485212-dc2db986-b5c6-4b2c-9919-a12b25d3be48.png)
![image](https://user-images.githubusercontent.com/37758451/170485236-4ff1ce03-ebae-4785-8973-a7d8994a3555.png)
![image](https://user-images.githubusercontent.com/37758451/170485246-fbca2fc5-fa54-4967-9255-9ee9a2251fcd.png)

**Comment by cwk0099** [comment]
path设置成./test_cases的话就只执行login，不执行api文件夹里面的

**Comment by defnngj** [comment]
给子目录加一个空的 __init__.py 初始化文件（用来标识一个目录为 python 模块）。这样框架就能检索到子目录的用例了。

```
test_cases   # 测试用例目录
    ├── __init__.py     # 初始化文件
    ├── user   
    │   ├── __init__.py    # 初始化文件
    │   ├── case/   
    │   │    ├── __init__.py   # 初始化文件
    │   │    ├── test_xxx.py
    │   │    └── test_xxx.py

```

**Comment by cwk0099** [comment]
> 给子目录加一个空的 __init__.py 初始化文件（用来标识一个目录为 python 模块）。这样框架就能检索到子目录的用例了。
> 
> ```
> test_cases   # 测试用例目录
>     ├── __init__.py     # 初始化文件
>     ├── user   
>     │   ├── __init__.py    # 初始化文件
>     │   ├── case/   
>     │   │    ├── __init__.py   # 初始化文件
>     │   │    ├── test_xxx.py
>     │   │    └── test_xxx.py
> ```

好的谢谢！
