### ISSUE TITLE
有人知道urllib3.connectionpool日志记录怎么屏蔽吗？万分感谢

### ISSUE THREAD

**Issue by Gary-CHAO1** [SeldomQA/seldom#116]
seldom==2.5.1

![error](https://user-images.githubusercontent.com/101296901/172339942-14bc6abd-3e34-41c7-973e-ed430e33d1e7.png)

**Comment by defnngj** [comment]
这个日志不是seldom 打印的，不确定是否和你 发送的http请求有关。

**Comment by Gary-CHAO1** [comment]
是urllib3的connectionpool.py里面的，上周跑都没有。找到源码直接给注释掉...
