### ISSUE TITLE
我在本地修改了HTML的样式，本地运行没问题，部署到jenkins又重置了

### ISSUE THREAD

**Issue by ranyong1997** [SeldomQA/seldom#117]
![Snipaste_2022-06-10_14-32-39](https://user-images.githubusercontent.com/67427627/173005024-da572ca8-3954-4fdc-a215-087c72005ef3.png)
![Snipaste_2022-06-10_14-32-59](https://user-images.githubusercontent.com/67427627/173005045-12de7c7b-a608-48a6-87b6-1a79880d39b8.png)
排查过 我即使在本地删除了XTestRunner这个文件，在本地运行肯定报错，但是push代码到jenkins中运行，它能正常跑，我依赖也没引入XTestRunner这个，可是为什么可以拉取到已经网络上原本的日志呢

**Comment by defnngj** [comment]
jenkins 上面 seldom 依赖的XTestRunenner 库是否是修改过的 还是 安装时自动化从 pipy 仓库拉取的？

**Comment by yongchin0821** [comment]
可能是因为安装seldom的时候会自动装XTestRunner

**Comment by ranyong1997** [comment]
> jenkins 很少依赖的 XTestRunenner 库是否是过的或者安装时自动化从 pipy 仓库拉取的？

我在req
![Snipaste_2022-06-13_15-37-52](https://user-images.githubusercontent.com/67427627/173303374-ad74b6ca-ddf9-49cf-a230-5b5835ed3217.png)
uirements.txt里面没有写入这个依赖

**Comment by ranyong1997** [comment]
> 可能是因为安装很少的时候会自动安装XTestRunner

我还在排查这个  我感觉是自动给我安装了，现在还不知道如果安装了，我的requirement.txt里面的内容为
```
async-generator==1.10
attrs==21.2.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.9
colorama==0.4.4
configparser==5.2.0
crayons==0.4.0
cryptography==36.0.1
et-xmlfile==1.1.0
h11==0.12.0
idna==3.3
importlib-resources==5.4.0
Jinja2==3.0.3
jmespath==0.10.0
jsonschema==4.3.1
MarkupSafe==2.0.1
openpyxl==3.0.9
outcome==1.1.0
parameterized==0.8.1
pycparser==2.21
pyOpenSSL==21.0.0
pyrsistent==0.18.0
PyYAML==6.0
requests==2.26.0
selenium==4.1.0
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
trio==0.19.0
trio-websocket==0.9.2
urllib3==1.26.7
webdriver-manager==3.5.2
wsproto==1.0.0
zipp==3.6.0
WorkWeixinRobot==1.0.1
locust==2.8.1
loguru==0.6.0
```

**Comment by yongchin0821** [comment]
我的意思是，安装seldom的时候，会自动安装依赖的XTestRunner。这个和你requirement.txt没有关系的

你本地修改了XTestRunner，你得去执行的环境替换XTestRunner，才能生效

**Comment by ranyong1997** [comment]
> 我的英文是，安装很少的时候，会自动安装依赖的 XTestRunner。这个和你requirement.txt没有关系的
> 
> 你本地修改了 XTestRunner，你得去执行替换 XTestRunner，的生效环境

醍醐灌顶！感谢
