### ISSUE TITLE
测试报告，统计结果有问题

### ISSUE THREAD

**Issue by jingyuezijing** [SeldomQA/seldom#121]
**问题1：**
![image](https://user-images.githubusercontent.com/77383326/175868948-8df768ee-2a0d-46ff-bca3-f088d2ca8a01.png)
rerun=1，如图查看failed结果，有2条用例执行失败，但是总数统计的失败是1
**问题2：**
![image](https://user-images.githubusercontent.com/77383326/175868448-697c8ee0-1715-41f6-9d66-5cf5b6c5fb8b.png)
1)如图，当前用例集合下有多条用例，但是只执行了4条，其他的skip了
2）summary视图下，就只显示4条用例，按顺序显示了4条
预期
应该去除skip的，显示所有执行过的用例
ce测试报告见附件
[report (31).zip](https://github.com/SeldomQA/seldom/files/8988992/report.31.zip)

**Comment by defnngj** [comment]
__问题一__

`rerun=1` 当用例执行失败时重跑一次。`rerun: 1`  就是重跑一次的结果了。

![image](https://user-images.githubusercontent.com/1000588/176113114-af5125ab-bbc5-4623-94f7-fe7c76961a8c.png)

所以，显示两条错误，统计为`1条`用例失败。 这应该没错~！

**Comment by jingyuezijing** [comment]
> **问题一**
> 
> `rerun=1` 当用例执行失败时重跑一次。`rerun: 1` 就是重跑一次的结果了。
> 
> ![image](https://user-images.githubusercontent.com/1000588/176113114-af5125ab-bbc5-4623-94f7-fe7c76961a8c.png)
> 
> 所以，显示两条错误，统计为`1条`用例失败。 这应该没错~！

确定是两条，用例名称和参数输入的都是不一样。
