### ISSUE TITLE
建议大版本的迭代行为打上对应的release-tag

### ISSUE THREAD

**Issue by MarinPeng** [SeldomQA/seldom#123]
因为项目的快速迭代导致的文档和对应接口的修改使用方式不同，同时也建议保留不同版本的文档以供使用者快速浏览

**Comment by defnngj** [comment]
建议很好，后续版本添加  release 

seldom的每个版本变更的内容在: `CHANGES.md` 是有说明的
https://github.com/SeldomQA/seldom/blob/master/CHANGES.md

> 你可以通过该文档了解到每个版本的更新。
