### ISSUE TITLE
 ding.sender()能否扩展下，支持：自定义data，发送指定的内容？

### ISSUE THREAD

**Issue by jingyuezijing** [SeldomQA/seldom#125]
因为gitlab CI上执行结束后，发送信息，希望发送自定义的一些内容：
如：用例通过率，代码覆盖率，以及pipeline的链接等信息
预期：
建议扩展：希望可支持完全自定义（即覆盖内容），或者追加自定义内容两种方式

**Comment by defnngj** [comment]
好建议， 接下来会实现lark消息的支持，到时候一并支持钉钉消息的自定义。

**Comment by jingyuezijing** [comment]
> 好建议， 接下来会实现lark消息的支持，到时候一并支持钉钉消息的自定义。

希望可支持：完全自定义（即覆盖内容），或者追加自定义内容两种方式。

**Comment by defnngj** [comment]
seldom 不需要升级，只升级 `XTestRunner==1.4.4` 版本

参考文档：https://github.com/SeldomQA/XTestRunner/blob/master/docs/send_notice.md#%E5%8F%91%E9%80%81%E9%92%89%E9%92%89

`sender()` 增加两个参数：

* append: 在发送的消息中追加一些消息，markdown的字符串格式， 例如"\n#标题 \n*id \n*名字"
* text: 替换要发送的消息，markdown的字符串格式。
