### ISSUE TITLE
【问题】测试报告中，失败数统计错误

### ISSUE THREAD

**Issue by 792817377** [SeldomQA/seldom#126]
测试报告中，失败数统计错误，如图，本身有十几个用例错误了，但是只统计到1个失败
main中设置rerun=3，不知道这个是否有影响

![9IDQ{$KZ9VRCX(JVFB_@BW7](https://user-images.githubusercontent.com/102853018/178453714-65ec5bbd-5978-4855-b583-5af9c9c8754c.png)

**Comment by 792817377** [comment]
如图，可以看到，断言是在testcase里面的，其他失败的也都是
![image](https://user-images.githubusercontent.com/102853018/178456326-6a3d6d4f-baab-47e1-9cd8-108c79617fc4.png)
![image](https://user-images.githubusercontent.com/102853018/178456711-a38dc28a-004c-4ce9-a960-be260dcaa742.png)

**Comment by 792817377** [comment]
发现如果不配置return，统计的错误数就是正确的，如果配置了return，如return=3，数量统计就错误

**Comment by jingyuezijing** [comment]
> 发现如果不配置return，统计的错误数就是正确的，如果配置了return，如return=3，数量统计就错误

/issues/121  我也遇到同样的问题。
@defnngj 
求快点修复呀  我要把测试报告发布到公司gitlab的站点上去。现在都是设置的rerun=0

**Comment by defnngj** [comment]
现在已没这个问题，哪个版本解决的无法追查，请使用最新版本。
