### ISSUE TITLE
关于测试用例集编排的问题

### ISSUE THREAD

**Issue by Luna-CY** [SeldomQA/seldom#129]
问题：

现在通过TestMainExtend类来执行指定的测试用例时，其执行流程为通过TestMain方法加载`path`指定的所有测试用例，并在执行时根据`TestMain.TestSuites`列表的加载顺序来添加测试用例，这就有一个问题，`TestMain.TestSuites`加载的顺序是用例在文件夹中的字典序，这个顺序与传入给`TestMainExtend.run_cases`方法的顺序可能不符，从用例编排的角度来讲，这里应该使用传入`TestMainExtend.run_cases`方法的用例列表顺序来执行更为自然

修复：

调整`TestMainExtend.run_cases`方法添加用例的顺序为传入的用例顺序

**Comment by Luna-CY** [comment]
在最新分支修改的时候发现一个问题，`https://github.com/SeldomQA/seldom/blob/66e5a0279fda31b4c0205814009df7512f68e891/seldom/running/runner.py#L283`这里从测试用例名称的前缀匹配，这个是出于哪方面的设计考虑的？

**Comment by Luna-CY** [comment]
@defnngj 您好，能否回答一下上面的问题，讨论一下这里的设计和实现

**Comment by defnngj** [comment]
https://github.com/SeldomQA/seldom/issues/128

**Comment by defnngj** [comment]
你可以加官方QQ群：948994709 ，我平时都会在里面解答seldom 框架的各种问题。

#128  我解答了 seldom 收集和执行用例的 方式。其实官方问题也说的比较清楚了。

用例名称的前缀匹配是考虑到 数据驱动。我们并想不解析数据驱动的每个数据为一条用例。因为我们的数据驱动需要适配环境。也就说根据测试环境 读取不同 数据驱动文件。如果数据驱动被解析成具体的用例，那么就不能再根据环境 去执行不同的用例了。

**Comment by Luna-CY** [comment]
对于用例的搜集和执行拆分是没有问题的。

[#128] 问题其实是用例搜集完成后，开始执行之前，driver被关闭了的问题，与具体的driver类型也是没关系的。

当前这个问题其实执行时的顺序编排问题，当前`run_cases`执行用例时，并不是按照给定的用例列表顺序来执行，而是通过搜集到的用例顺序，搜集用例时的顺序其实是文件名称的字典序，这个顺序与传入`run_cases`方法的期望顺序可能是不一致的

例如以下示例

```
|-- test_dir/
|-- |-- test_password_login.py
|-- |-- test_logout.py
```

```
suite = [
  {"file": "test_password_login","class": {"name": "PasswordLoginTest"},"method": {"name": "test_login"}},
  {"file": "test_logout","class": {"name": "LogoutTest"},"method": {"name": "test_logout"}},
]

main_extend.run_cases(suite)
```

从用例搜集的顺序来看，`test_logout.py`的字典序优于`test_password_login.py`，但是从用例执行的顺序来编排，显然应该是先登录，后退出，这符合传递给`run_cases`方法的顺序

因此，问题实质上是在执行用例时，用例的遍历主体是错的，在文件`https://github.com/SeldomQA/seldom/blob/master/seldom/running/runner.py#L302`这一行，遍历的主体是搜集的顺序，然后验证是否在给定用例中，这就导致传入给`run_cases`方法的用例顺序是无效的

**Comment by defnngj** [comment]
在用例设计上应该避免依赖，如果不存在依赖关系，先被执行或后被执行不那么重要。

不过，这里可以优化一下，将循环的测试套件和 `run_cases ` 接收到的用例对调即可。
