### ISSUE TITLE
获取用例信息:有中文的名称，中文字符会丢失

### ISSUE THREAD

**Issue by jingyuezijing** [SeldomQA/seldom#135]
![image](https://user-images.githubusercontent.com/77383326/180992079-ea5849cb-2f7f-4720-a069-aeca719349fe.png)
获取用例信息:有中文的名称，中文字符会丢失，如图

**Comment by defnngj** [comment]
是这样的，所以在 `seldom 2.10.3` 版本不在使用参数化的第一个参数作为用例名称的一部分了。

1. 参数化的用例名称只加`下划线`+`编号`：`_0` 、`_1` 、`_2` ... 

2. 测试报告只显示参数化数据的第一个字段，所以，可以将第一个字段作为用例的`说明` 

![U04HH QS2DXJ`4EXQ8B{~$Q](https://user-images.githubusercontent.com/1000588/181061295-ce2ba164-f396-446e-9802-10783b02809c.jpg)


相关：https://github.com/SeldomQA/seldom/issues/124
