### ISSUE TITLE
clear()方法无法使用

### ISSUE THREAD

**Issue by sobbingchild** [SeldomQA/seldom#141]
文档链接：https://github.com/SeldomQA/seldom/blob/master/docs/rst_docs/seldom_api.rst
![image](https://user-images.githubusercontent.com/66291315/186842253-d97740ed-610b-4541-aa6e-e0e6d62e6ad7.png)
根据文档内容使用clear方法，发现无法清除输入框内容，报告展示已经执行，但是并未产生任何效果
self.clear(css="#el")
![image](https://user-images.githubusercontent.com/66291315/186842770-358e9bcc-ec08-4474-a280-13447fc24fa7.png)
![image](https://user-images.githubusercontent.com/66291315/186842556-d0391ff0-c8f2-472c-a333-9e79b444b31c.png)

**Comment by defnngj** [comment]
`clear()` 封装的selenium 的方法，如果是输入框，并且是可以输入的内容；是可以清空的； 如果无效，你可以试试js的方式。比如：

```js
document.querySelector("#id").value = ""
```

seldom 可以执行

```py
self.execute_script('document.querySelector("#id").value = ""')
```
