### ISSUE TITLE
Seldom 运行 self.get 用例返回非 json , 数据为乱码

### ISSUE THREAD

**Issue by imvkmark** [SeldomQA/seldom#146]
demo repo:
https://github.com/imvkmark/seldom-debug

command: 
```
seldom -r run.py
```

screenshot:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/150127/193876264-154aa368-0c96-4757-a38d-cac97ae3b4f2.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/150127/193876489-ee1bf5d0-348b-43de-b742-1ac3d4651b3b.png">

**Comment by defnngj** [comment]
seldom 主要用来做http接口测试的，你调用的是一个HTML页面。

不过，这个问题已经修复了，参考->：https://github.com/SeldomQA/seldom/commit/111be91e58e97ca56aca52b77f73f85f7146d658

感谢反馈~！

**Comment by imvkmark** [comment]
反应好迅速, 不过这样的解决方法遇到 gbk 也是会挂的, 不过当前世界 gbk 网站应该也是了了了, 谢谢修复
