### ISSUE TITLE
运行test_case时报cannot import name 'TestCase'

### ISSUE THREAD

**Issue by zhou-xiaoming** [SeldomQA/seldom#15]
运行报错：cannot import name 'TestCase'，望尽快修复哈

**Comment by defnngj** [comment]
请粘贴一个运行方式，以及完整的报错！

**Comment by zhou-xiaoming** [comment]
————————————————————————————————————
周晓明 Himin
软件测试
上海闪派信息技术有限公司
办公地址：上海市浦东新区如日商务园403室
手机：18552053546
