### ISSUE TITLE
【需求】增加支持连接SqlServer数据库

### ISSUE THREAD

**Issue by 792817377** [SeldomQA/seldom#154]
例如：
    def query_sql(self, sql):
        """
        执行查询语句
        返回的是一个包含tuple的list，list的元素是记录行，tuple的元素是每行记录的字段

        """
        data_list = []
        cur = self.__GetConnect()
        cur.execute(sql)
        rows = cur.fetchall()
        for row in rows:
            data_list.append(row)
        #查询完毕后必须关闭连接
        self.conn.close()
        return data_list

**Comment by defnngj** [comment]
我对 SQL server 的使用还停留在大学时期，周末安装一下； 实现以下相关API。

或者，你是否有能力开发，或 帮助测试? 

参考代码：https://github.com/SeldomQA/seldom/tree/master/seldom/db_operation

**Comment by 792817377** [comment]
以下的代码，是我自己目前在用封装的，可以参考下，若是seldom也做了，目前在写相关脚本，可测试下调用使用

import pymssql

class MSSQL:
    def __init__(self, host, user, pwd, db):
        self.host = host
        self.user = user
        self.pwd = pwd
        self.db = db

    def __GetConnect(self):
        """
        得到连接信息
        返回: conn.cursor()
        """
        if not self.db:
            raise(NameError, "没有设置数据库信息")
        self.conn = pymssql.connect(host=self.host, user=self.user, password=self.pwd, database=self.db, charset="cp936")    # cp936:因为有的中文返回乱码，所以用这个  
        cur = self.conn.cursor(as_dict=True)    #
        if not cur:
            raise(NameError, "连接数据库失败")
        else:
            return cur

    def query_sql(self, sql):
        """
        执行查询语句
       
        """
        data_list = []
        cur = self.__GetConnect()
        cur.execute(sql)
        rows = cur.fetchall()
        for row in rows:
            data_list.append(row)
        #查询完毕后必须关闭连接
        self.conn.commit()
        self.conn.close()
        return data_list

     
    def execute_sql(self, sql):
        """
        执行非查询语句
        """
        cur = self.__GetConnect()
        cur.execute(sql)
        self.conn.commit()
        self.conn.close()

**Comment by defnngj** [comment]
你可以尝试为 seldom 提 pr :  https://blog.csdn.net/qq_33429968/article/details/62219783

**Comment by defnngj** [comment]
@792817377 SQL Server 已经在 seldom==3.0.1  版本做了支持; 

需要单独执行pip 安装 pymssql

```shell
> pip install pymssql
```

文档：

https://github.com/SeldomQA/seldom/blob/master/docs/vpdocs/db/db_operation.md
