### ISSUE TITLE
当弹出框是prompt提示框时，需要输入文本，seldom中怎么处理？

### ISSUE THREAD

**Issue by tzk1986** [SeldomQA/seldom#166]
测试用网站：https://liushilive.github.io/html_example/index.html
使用seldom进行web自动化，在prompt提示框时需要输入文本
![image](https://user-images.githubusercontent.com/103291191/220251044-093cdde5-1de6-4016-af80-ee1b0caed18b.png)
在使用seleium时，可以选择`switch_to.alert`，然后直接`send_keys`如下
![image](https://user-images.githubusercontent.com/103291191/220257019-0213dd29-3425-40c2-858f-d43df740b3cd.png)
在seldom中没有`switch_to.alert`，有的是直接获取警告信息或者确定和取消，链式处理Steps中有alert，但是无法实现输入
`s.find("#b2").click().alert().type("shishi")
        s.accept()`
![image](https://user-images.githubusercontent.com/103291191/220258084-e02b1786-0421-4c20-8664-dd67f2237a44.png)

**Comment by defnngj** [comment]
seldom 的链式调用： `alert().type("shishi")`  其中， `type()` 是针对普通输入框的。 目前警告框上面的输入不支持。


seldom 中没有封装 警告框的输入方法。你可以按照selenium 的方法用, 参考：

![image](https://user-images.githubusercontent.com/1000588/220274692-6f30d00e-1009-4231-9b43-babe869f19da.png)

**Comment by defnngj** [comment]
我又尝试了一下。 selenium 提供的 `switch_to.alert.send_keys()` 不能操作 prompt 的输入。

**Comment by tzk1986** [comment]
嗯，不过测试网站上，使用`switch_to.alert.send_keys()`，在返回的警告框的信息上，是展示输入的数据的。不知道是不是selenium内部有处理。
![image](https://user-images.githubusercontent.com/103291191/220535830-f23ee309-7f35-47eb-86c8-96201d54339b.png)
我还看了下其他[博客](https://www.cnblogs.com/Neeo/articles/11465005.html#selenium%E5%A4%84%E7%90%86prompt%E6%8F%90%E7%A4%BA%E6%A1%86)
里面有说到selenium的 prompt 的输入处理，应该是可行的。

**Comment by yanxin152133** [comment]
![image](https://github.com/SeldomQA/seldom/assets/43341537/65012168-d31e-4331-84be-00907f5e83c2)
![image](https://github.com/SeldomQA/seldom/assets/43341537/168edc8b-6b03-4e0a-822f-12be13e5fa3a)

**Comment by defnngj** [comment]
`seldom==3.9.1` 增加 `prompt_value()` 用法，针对弹窗上的输入框输入。
