### ISSUE TITLE
Use the pip command to install seldom. zsh cannot find seldom

### ISSUE THREAD

**Issue by XuXuClassMate** [SeldomQA/seldom#167]
install:
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/76080484/220261717-04cef8a9-5976-41f1-906d-29426d1b0920.png">

use:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/76080484/220261605-25968100-8e7f-493c-85a1-585e30bf41bd.png">

**Comment by defnngj** [comment]
![image](https://user-images.githubusercontent.com/1000588/220269186-8236224b-a5b4-44d0-b5a6-fcda38a0528c.png)

默认会生成到 `/usr/local/bin/seldom`

如果你使用了虚拟环境， 要看python 的路径， 例如：

```shell
# python
/Users/user/.local/share/virtualenvs/seldom-qUWgROyJ/bin/python
# seldom
/Users/user/.local/share/virtualenvs/seldom-qUWgROyJ/bin/seldom
```

根据你的安装，你可以在这个路径下找找：
![image](https://user-images.githubusercontent.com/1000588/220269991-549480ca-6cc1-4234-9850-d84725ef7465.png)

**Comment by XuXuClassMate** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/76080484/220296845-320ecb12-972b-4106-8070-ac9ab3d966af.png">


<img width="839" alt="image" src="https://user-images.githubusercontent.com/76080484/220296930-9e24b78f-bc99-4d0e-8200-a6159c6ecd1a.png">


When I use the install command to download,/usr/local/bin/seldom is not generated by default

Is there any entrance to resume soft links?

**Comment by XuXuClassMate** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/76080484/220318934-ff0521f5-709b-46c6-aac3-218260a87333.png">

I saw his directory when I was about to uninstall and reload. I hope this is a new "FQA" for us . cc @defnngj 

Then establish the soft connection

`sudo ln -s /Library/Frameworks/Python.framework/Versions/3.10/bin/seldom /usr/local/bin/seldom`

**Comment by XuXuClassMate** [comment]
Thank you very much for your help
