### ISSUE TITLE
使用框架打开F12的手机模式

### ISSUE THREAD

**Issue by buzheng1943** [SeldomQA/seldom#17]
您好虫师，请问怎么完成Chrome浏览器用手机模式打开网页的操作呢？

**Comment by defnngj** [comment]
已支持手机模式：
https://seldomqa.readthedocs.io/en/latest/rst_docs/other.html

**Comment by defnngj** [comment]
新的配置：https://seldomqa.github.io/web-testing/other.html#mobile-web-%E6%A8%A1%E5%BC%8F
