### ISSUE TITLE
【问题】最新版本3.2.0，无法正常发送邮件，需把smtp.starttls()注释

### ISSUE THREAD

**Issue by 792817377** [SeldomQA/seldom#177]
发送邮件这里，报错【STARTTLS extension not supported by server.】，需把smtp.starttls()注释，才可以发送成功
![image](https://user-images.githubusercontent.com/102853018/230572348-7fe3b5e5-3222-42e8-ba89-791b3a7092e2.png)

![image](https://user-images.githubusercontent.com/102853018/230572302-b03e70b2-0f1f-481a-b600-1957356b16cd.png)

**Comment by defnngj** [comment]
升级 `XTestRunner=1.6.3` 版本:

增加了 tls 开关，设置为 False 即可。
![image](https://user-images.githubusercontent.com/1000588/230641074-e336a788-48d3-4475-949c-cc1eea2ae946.png)

感谢反馈。
