### ISSUE TITLE
运行用例日志等级支持自定义传入

### ISSUE THREAD

**Issue by boyli698** [SeldomQA/seldom#178]
![image](https://user-images.githubusercontent.com/12146363/233992931-af2a923b-187e-46d7-9dfe-036b734c7a64.png)
![image](https://user-images.githubusercontent.com/12146363/233993045-550ba869-a6fd-4c9d-80dd-a11df493643a.png)

**Comment by wu-clan** [comment]
如果你是此项目维护人员，可以手动修改文件配置
```python
# log level: TRACE < DEBUG < INFO < SUCCESS < WARNING < ERROR
log_cfg = LogConfig(level="TRACE")
```

如果你是此项目使用者，需在命令行使用 -ll 或 -log-level 参数指定
```
-ll, --log-level [TRACE|DEBUG|INFO|SUCCESS|WARNING|ERROR] Set the log level.
```
