### ISSUE TITLE
问下现在app测试是怎么调用的？我看seldom.main()方法中没有文档中的用法了

### ISSUE THREAD

**Issue by Gary-CHAO1** [SeldomQA/seldom#179]
'appActivity': '.ui.LoadingActivity',
        'noReset': True,
    }
    seldom.main(app_info=desired_caps, app_server="http://127.0.0.1:4723")

**Comment by defnngj** [comment]
https://github.com/SeldomQA/seldom/blob/master/seldom/running/runner.py

通过 `app_server` 和 `app_info` 两个参数：
![image](https://user-images.githubusercontent.com/1000588/234323957-dcbbc6cf-9ee3-4940-a246-fc9c9465808f.png)

**Comment by Gary-CHAO1** [comment]
> https://github.com/SeldomQA/seldom/blob/master/seldom/running/runner.py
> 
> 通过 `app_server` 和 `app_info` 两个参数： ![image](https://user-images.githubusercontent.com/1000588/234323957-dcbbc6cf-9ee3-4940-a246-fc9c9465808f.png)
看到了，我之前装的2.10.1，谢谢虫师
