### ISSUE TITLE
使用seldom -install 提示出错

### ISSUE THREAD

**Issue by moguangjian** [SeldomQA/seldom#18]
报错如下
usage: seldom [-h] [-V] [--startproject STARTPROJECT] [-r R]
seldom: error: unrecognized arguments: -install chrome

**Comment by defnngj** [comment]
1、最新的 0.3.5 版本支持，请检查是不是最新版本。
2、安装命令：
```shell
seldom -install  chrome   //安装chromedriver
seldom -install  firefox    //安装geckodriver
```

**Comment by moguangjian** [comment]
确实是版本的问题，谢谢
