### ISSUE TITLE
运行时出现了“系统找不到指定的文件”的错误

### ISSUE THREAD

**Issue by moguangjian** [SeldomQA/seldom#19]
File "c:\program files (x86)\python36-32\Lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

我查找了一下，说是webdriver的路径不对，但我已经在项目目录下使用了`seldom -install chrome`，在lib目录下已经有chromedriver，还需要指定chromedriver 的绝对路径吗? 谢谢

**Comment by klookAppTest** [comment]
seldom 只是帮你把 浏览器驱动下载下来，你需要指定驱动文件的绝对路径，或者将绝对路径添加到 环境变量 `path`下面。 
```python
import seldom

# ...

if __name__ == '__main__':
    seldom.main(path="./",
              browser="chrome",
              driver_path="D://driver/lib/chromedriver",
    )
```
driver_path指定 驱动路径。

或者将：
D://driver/lib/
添加到环境变量path下面

**Comment by moguangjian** [comment]
明白了，谢谢。我将chromedriver放到了虚拟环境中python所在的目录也能运行成功
