### ISSUE TITLE
如何循环运行测试用例

### ISSUE THREAD

**Issue by wupo0709** [SeldomQA/seldom#20]
想问下是否可加入用例运行次数的参数，使某一个用例不管pass与否都能可多次执行

**Comment by defnngj** [comment]
用例失败了可以重跑，用例成功了为什么要循环执行? 你可以将 循环的步骤写到一个用例里面。

**Comment by wupo0709** [comment]
> 用例失败了可以重跑，用例成功了为什么要循环执行? 你可以将 循环的步骤写到一个用例里面。
1、用例失败可以有很多种情况触发，同样用例跑成功了并不代表下一次同样的操作就不会出问题啊；
2、所以我想某一个用例多次长时间运行，目前看来只有在这条用例里加循环，这样导致生成的测试报告种该条用例比如循环了100次，但其中有若有一次循环失败了，报告只算该条用例失败；

**Comment by defnngj** [comment]
> 同样用例跑成功了并不代表下一次同样的操作就不会出问题啊；

你可以将你的自动化项目连着跑3(或N)遍，因为你说了1遍成功 __不能证明真的成功__。

如果你想对自动化项目的某条用例跑3（或N）遍，其他用例跑1遍？那这就不行了。你说了一遍的成功不代表成功。所以，必须全部都要3(或N)遍。

所以，根本不存在针对某个用例循环跑几遍这样的需求，我没有看到过有自动化框架支持某个用例不管成功与否强制设置跑几遍的功能，你可能对自动化测试的一些概念和思想有设么误解。
