### ISSUE TITLE
【问题】confrun.py修改默认配置未生效，怎么让报告默认语言为中文

### ISSUE THREAD

**Issue by SCP-QQ** [SeldomQA/seldom#205]
修改报告默认语言为中文没有生效
![image](https://github.com/SeldomQA/seldom/assets/63279924/94b7b057-27f5-44f8-b804-3983842b64f7)
  
使用run.py报告可以变为中文
![Snipaste_2023-11-29_09-50-33](https://github.com/SeldomQA/seldom/assets/63279924/0a0ff619-f3df-4046-95d0-851ebe0982b6)

**Comment by defnngj** [comment]
你的用法不太对，参考：
* 首先，我的目录结构如下：
```
>  tree
.
├── confrun.py  # 运行配置文件。
├── reports
│   ├── 2023_11_30_11_46_02_result.html
│   └── seldom_log.log
├── test_data
│   └── data.json
└── test_dir
    ├── __init__.py
    └── test_api_sample.py
```
* confrun.py 配置

```python
...
def language():
    """
    setting report language
    """
    return "zh-CN"

....
```

运行测试，必须在 `confrun.py ` 所在目录运行。
```bash
> ls     # 查看当前目录文件    
confrun.py	reports	est_data  	test_dir

> seldom -p test_dir  # 指定用例目录
```

* 生成的报告是中文的了

![image](https://github.com/SeldomQA/seldom/assets/1000588/fd238a1b-d03e-4d32-b030-e56646137285)

**Comment by SCP-QQ** [comment]
好的，多谢，解决了
