### ISSUE TITLE
【问题】 self.max_window() 方法报错，虽然执行成功了，但是有个报错，浏览器并没有最大化

### ISSUE THREAD

**Issue by kingDaima** [SeldomQA/seldom#216]
版本信息：
Name: seldom
Version: 3.6.0
Summary: Seldom automation testing framework based on unittest.
Home-page: https://seldomqa.github.io
Author: bugmaster
Author-email: fnngj@126.com
License: Apache-2.0

代码：
import seldom

class BaiduTest(seldom.TestCase):
    """
    * start_class/end_class
    * start/end
    """
 
    def start_class(self):
        """start class"""
        print("test class start")
        self.max_window()

报错：
test class start
2024-03-15 10:42:10 | ERROR    | case.py | start_class Exception: 'NoneType' object has no attribute 'maximize_window'
test_case1 (test_fixture_demo.BaiduTest.test_case1) ... test case start

**Comment by defnngj** [comment]
代码没问题，应该运行方式有关，seldom 的执行入口是 `seldom.mian()` 方法。很可能是在 pycharm 中右键某个方法执行。 

* 查看文档 [运行方式](https://seldomqa.github.io/getting-started/quick_start.html#%E8%BF%90%E8%A1%8C%E6%B5%8B%E8%AF%95)

**Comment by netassa** [comment]
> @defnngj 我也遇到了，是使用python run.py的方式执行的：
> 
> ```
> def start(self):
>     self.login_page = LoginPage()
>     print("hello")
>     self.max_window()
> ```
> 
> 报告提示如下： ![image](https://private-user-images.githubusercontent.com/17811689/323119274-394a889c-432d-4c5b-8ffb-89084d5c2bf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDgxMjEsIm5iZiI6MTcxMzM0NzgyMSwicGF0aCI6Ii8xNzgxMTY4OS8zMjMxMTkyNzQtMzk0YTg4OWMtNDMyZC00YzViLThmZmItODkwODRkNWMyYmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA5NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZDM2ODc0NmUxYWJjOGI4NDA1ZjYxZGRkNTNkMWVkNzA2ZTk2MzQ1YjA1M2FmOTAyNTE5NGZiMjJmNTRlNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9HqCNUVPiN6QHfVKzCqii3MDPfxlxXS43zm23tcIMNg)

好像知道原因了，是因为调用self.max_window()的时候，浏览器还没起来。
