### ISSUE TITLE
关于每个用例的日志记录探讨

### ISSUE THREAD

**Issue by yuanroc** [SeldomQA/seldom#22]
针对日志记录是否有必要：
A：针对每一个测试用例文件如test1.py 生成对应的专门日志文件吗？
B：还是说日志生成的时候，就会告诉你执行的那一个 *.py文件，执行那个类，执行了那个测试方法？

再引入两个小问题：如何保证以下日志的易用性和整体性！
1、若分布式怎么记录日志？
2、若需要多线程的时候，这个日志又怎么记录？

**Comment by klookAppTest** [comment]
为什么要日志？ 生成的测试报告不上不出是哪个文件的哪个用例失败了？ 是要是代码运行的错误都可以通过报告查看。 

多线程 unittest 不支持，就算支持， UI 自动化也建议通过多线程的方式来运行。
