### ISSUE TITLE
Web UI 自动化测试建议可以手动初始化 driver 

### ISSUE THREAD

**Issue by xianyiLuo** [SeldomQA/seldom#224]
```
    def test_case(self):
        """
        A simple test
        """
        page = BaiduPage(self.driver, print_log=True)
        page.open("https://www.baidu.com")
        page.search_input.send_keys("seldom")
        page.search_button.click()
        self.assertTitle("seldom_百度搜索")

```

官方 Web UI 测试 - Page Object 文档中的教程，这段代码 `page = BaiduPage(self.driver, print_log=True)`，这里传入 self.driver 是 None，会报错，主动赋值 self.driver 显示为只读属性，只能通过 `self.open()` 才能初始化 driver

**Comment by xianyiLuo** [comment]
看了源代码发现`seldom.Tecase` 发现有个 browser() 可以解决上面问题。

**Comment by wcaojinj1314** [comment]
我好像也碰到了类似问题，大神请教下
@classmethod
def start_class(cls):
    page = login_page.LoginPage(cls.driver)
    page.open(BASE_URL)
    page.login(LOGIN_USER,LOGIN_PASSWORD)
     
@classmethod
def end_class(cls):
    page = login_page.LoginPage(cls.driver)
    page.open(DASHBOARD_URL)
    page.login_out()

web自动化，我用seldom框架，测试用例里写的start_class方法，在测试类之前执行，但是执行的时候报下面的的错误
2025-11-16 14:02:10 case.py | MainThread | ERROR | start_class Exception: 'property' object has no attribute 'get'



这是我的LoginPage
from poium import Page, Element

class LoginPage(Page):
	username_text = Element("#div.slot-input-container > input", describe="邮箱输入框")
        password_text = Element("#div.slot-input-container > input", describe="密码输入框")
        button = Element("#button > span > span",describe="登录按钮")


	def login(self,username,password):
	    self.username_text.send_keys(username)
	    self.password_text.send_keys(password)
	    self.button.click()
