### ISSUE TITLE
【bug】测试用例脚本中不能使用变量id，会与源码中冲突

### ISSUE THREAD

**Issue by xiaoli1232001** [SeldomQA/seldom#225]
![1d9b7aeb3d8f4415b85a77969d5cf78](https://github.com/SeldomQA/seldom/assets/20430275/6070d5ac-cfb4-4f34-aa24-ce1ac2151f19)
![b42554b746150c1c85718d8fe60a788](https://github.com/SeldomQA/seldom/assets/20430275/a6304c1a-f691-4d79-a64d-53163f71ebf7)

**Comment by defnngj** [comment]
确实会有冲突，属于`self.id` 属于关键字，请避免 在 继承了 `seldom.TestCase` 的子类中使用 `self.id` 即可。
