### ISSUE TITLE
显示等待和隐示等待的api建议加载文档内

### ISSUE THREAD

**Issue by Phil-Xue** [SeldomQA/seldom#23]
显示等待和隐示等待的api建议加载文档内

**Comment by klookAppTest** [comment]
隐式等待文档里面有：
https://github.com/SeldomQA/seldom/blob/master/docs/seldom_api.md

```py
self.wait(10)
```

显式等待，通过`seldom.main()` 方法的 `timeout` 全局控制。

```py
import seldom

# ...

if __name__ == '__main__':

    seldom.main(
              timeout=None
    )
```

但，其实根本不需要关心每个元素的显示等待，seldom 已经帮你封装好了。
