### ISSUE TITLE
使用self.execute_script()方法，return 元素属性值 失败，结果为None

### ISSUE THREAD

**Issue by tumaowolf** [SeldomQA/seldom#26]
self.exectue_script(return 元素位置.元素属性)
返回的全是None

**Comment by tumaowolf** [comment]
我写了个简单例子

`import seldom
from seldom import Seldom
from poium import Page

class testPage(Page):
    test_url = "https://www.baidu.com"
    id = "quickdelete"
    #title的值 = "清空
    title_js = 'document.getElementById("quickdelete").title'

class testClass(seldom.TestCase):
    def test_now(self):
        page = testPage(Seldom.driver)
        self.open(page.test_url)
        title_value = self.execute_script("return "+page.title_js)
        self.assertEqual(title_value,"清空")`

title_value返回的就是None 

实际上我正在处理的项目的元素定位比较复杂，必须使用js脚本，求大神相助解决🙏

**Comment by klookAppTest** [comment]
改好了：
https://github.com/SeldomQA/seldom/commit/698fde7cdf35be4b7e2850ef34707682a7d084c0

**Comment by tumaowolf** [comment]
谢谢虫哥，已成功返回js值
