### ISSUE TITLE
run.py运行case时因浏览器驱动问题case没有执行

### ISSUE THREAD

**Issue by jhgyz** [SeldomQA/seldom#28]
run.py:
seldom.main(".\\dvm\\test_open.py",debug=False)
通过run.py运行无法执行case，但是单独运行test_open.pycase可以执行成功，浏览器驱动的路径已在环境变量中配置，因此main()没有传入此参数，但是查看seldom源码的test_runner.py和driver.py感觉当没有参数传入时并没有像webdriver.py中那样通过Seldom.driver.current_url获取driver path.请各位同学帮我看下这个问题。

**Comment by klookAppTest** [comment]
你使用的是相对路径，`run.py` 文件 和 `dvm\` 是在同一个目录下面吗？  如果不确定就使用绝对路径。例如：
`d:\\aa\bb\test.py` --> windows  
或者 
`/home/user/pro/test.py` --linux/macOS

**Comment by jhgyz** [comment]
已经解决，命令行里执行就没问题了
