### ISSUE TITLE
有提供修改浏览器代理的方法吗

### ISSUE THREAD

**Issue by ikoukou** [SeldomQA/seldom#31]
RT

**Comment by dengdeng11** [comment]
from seldom import ChromeConfig
from selenium.webdriver import ChromeOptions

if __name__ == '__main__':
  chrome_options = ChromeOptions()
  PROXY = "127.0.0.1:8888"
  chrome_options.add_argument('--proxy-server={0}'.format(PROXY))
  ChromeConfig.options = chrome_options
  seldom.main(browser="chrome")

**Comment by defnngj** [comment]
* 示例

```python
import seldom
from selenium.webdriver import ChromeOptions

if __name__ == '__main__':
    proxy = "127.0.0.1:1080"  # 示例代理地址和端口

    chrome_options = ChromeOptions()
    chrome_options.add_argument(f"--proxy-server={proxy}")
    browser = {
        "browser": "chrome",
        "options": chrome_options,
    }
    seldom.main(browser=browser)
```
