### ISSUE TITLE
select下拉选不了值，以下三种方法都试了，依然有问题，详细如下

### ISSUE THREAD

**Issue by ethan3030** [SeldomQA/seldom#35]
系统demo:
           <select name="NR" id="nr">
                <option value="10" selected="">每页显示10条</option>
                <option value="20">每页显示20条</option>
                <option value="50">每页显示50条</option>
            </select>

            self.select(css="#nr", value='20')
            self.select(css="#nr", text='每页显示20条')
            self.select(css="#nr", index=2)

笔者实际用例：
         <select id="ddlSource" name="ddlSource" class="form-control">
                  <option value="" data-i18n="TmTicketsAdd_V2.pSelect">请选择</option>
                   <option value="0" data-i18n="TmTicketsAdd_V2.tel">电话</option>
                   <option value="1" data-i18n="TmTicketsAdd_V2.weChat">微信</option>
                   <option value="2" data-i18n="TmTicketsAdd_V2.maibox">邮箱</option>
           </select>

           # self.select(css='#ddlSource',text='电话' )   list indices must be integers or slices, not NoneType
           # self.select(css="#ddlSource",value='0')      list indices must be integers or slices, not NoneType
           # self.select(css="#ddlSource",index=2)       list index out of range

跪求大佬看看

![image](https://user-images.githubusercontent.com/73167481/96569692-092dff00-12fc-11eb-9fca-2c6e9f8d92fa.png)

**Comment by defnngj** [comment]
问题已修复！
