### ISSUE TITLE
怎么支持多个class

### ISSUE THREAD

**Issue by tarzanfan** [SeldomQA/seldom#37]
比如:driver.find_element_by_css_selector('.new-tj2.active').click()
写成:type(css=".new-tj2.active")
定位不到

**Comment by defnngj** [comment]
请参考CSS 定位器：
https://www.w3school.com.cn/cssref/css_selectors.asp

**Comment by tarzanfan** [comment]
使用driver.find_element_by_css_selector('.new-tj2.active')能定位到，但是使用seldom语法type(css=".new-tj2.active")  这样定位不到

**Comment by defnngj** [comment]
可以的，例如：
```html
<a href="linkTest.htm" class="a x">Link Test</a>
```

seldom 定位 与 selenium 一致

```py
import seldom


class TestSome(seldom.TestCase):

    def test_case(self):
        """test case"""
        self.open("https://sahitest.com/demo")
        ee = self.get_elements(css=".a.x")
        for e in ee:
            print(e.text)

```
