### ISSUE TITLE
Chrome Driver 配置 DesiredCapabilities

### ISSUE THREAD

**Issue by chaosannals** [SeldomQA/seldom#39]
![截图](https://user-images.githubusercontent.com/8335358/102037012-1bf61900-3dff-11eb-86b6-a67134efdbd4.png)
chrome driver 创建时，只有远程的会应用 DesiredCapabilities 参数。
是否也给下面的加上？

**Comment by defnngj** [comment]
不使用远程不需要用到 `DesiredCapabilities ` 参数

**Comment by chaosannals** [comment]
`DesiredCapabilities.CHROME = {
        'browserName': 'chrome',
        "version": "",
        "platform": "ANY",
        'loggingPrefs': {
            'browser': 'ALL',
            'driver': 'ALL',
            'performance': 'ALL',
        },
        'goog:chromeOptions': {
            'perfLoggingPrefs': {
                'enableNetwork': True,
            },
            'w3c': False,
        },
    }`
我因为要配置 chrome 所以需要用到这个，要拿到请求后的响应信息。
请问 seldom 有获取请求信息之类的接口吗？

**Comment by defnngj** [comment]
支持浏览器更多启动配置：https://seldomqa.github.io/web-testing/other.html
