### ISSUE TITLE
要是能根据标签分组运行就更好了

### ISSUE THREAD

**Issue by chengguanghua** [SeldomQA/seldom#4]
一点小建议
1、要是能根据标签分组运行就更好了
2、用例中的业务逻辑和数据如何分离，页面元素发生变化后，如何以最小的代码修改量维护用例

**Comment by defnngj** [comment]
这个问题我问关，就只等着有一天来回复。

1. 用例标签分组功能终于支持了。 seldom 2.4.0 版本 
2. 业务逻辑和数据分离，可以使用参数化，这个很早就支持了。
