### ISSUE TITLE
PO方法疑惑

### ISSUE THREAD

**Issue by loveshanshan** [SeldomQA/seldom#41]
![image](https://user-images.githubusercontent.com/28916188/102610558-60b7e200-4168-11eb-915f-1a9b0cf55ee8.png)

**Comment by loveshanshan** [comment]
![image](https://user-images.githubusercontent.com/28916188/102610663-8ba23600-4168-11eb-88e5-cf7a50ec3bd2.png)

**Comment by defnngj** [comment]
1. `undefined ` 是因为定义的元素没有描述。

```
from poium import Page, NewPageElement


class BaiduIndexPage(Page):
    search_input = NewPageElement(name='wd', describe="百度输入框")
    search_button = NewPageElement(id_='su',  describe="百度搜索按钮")
```
建议给每个元素加上`describe`说明。

**Comment by loveshanshan** [comment]
收到，加了describe, 问题已解决，谢谢！
