### ISSUE TITLE
log日志中存在多余字符串

### ISSUE THREAD

**Issue by jingyuezijing** [SeldomQA/seldom#45]
https://user-images.githubusercontent.com/77383326/105152671-7000c580-5b42-11eb-9678-b02147df6484.png
**[32m**2021-01-20 16:59:19 [INFO] ✅ Find element: xpath=//*[@class='close-dlg-btn fv__icon-layer-close-white'] **[0m**
如图：生成的log中，有多余字符串
1）是因为log中进行了输出设置，不同等级的日志，用不同的颜色区别

**Comment by defnngj** [comment]
多余的字符在控制台是表示颜色的，暂时不知道怎么修复~！
