### ISSUE TITLE
seldom api 

### ISSUE THREAD

**Issue by loveshanshan** [SeldomQA/seldom#47]
没有看到检查元素是否存在的api； 使用场景，选择了不同的Type时，之前的页面元素会消失。然后再检查新的元素是否存在

**Comment by defnngj** [comment]
已增加对应的断言方法。

* 断言元素是否存在：
```python
self.assertElement(css="#kwasdfasdfa")
```
如果元素不存在，断言失败。

* 断言元素是否不存在：
```python
self.assertNotElement(css="#kwasdfasdfa")
```
如果元素存在，断言失败。

**Comment by defnngj** [comment]
`version 1.10.0` 版本已发布！可以再该版本使用这两个方法。

**Comment by loveshanshan** [comment]
![image](https://user-images.githubusercontent.com/28916188/106409602-dc04f700-647b-11eb-9805-7d8de5dda536.png)
![image](https://user-images.githubusercontent.com/28916188/106409696-1d95a200-647c-11eb-98f4-cc17edbb6fd3.png)
实际上想判断一个PO中的元素不存在，而不是再用例中再去写“css=XXXXX”

**Comment by loveshanshan** [comment]
self.assertNotElement(page_login.input_email, msg="XX元素未消失")
类似于这个使用方式，方便封装一个么，期望常用的定位元素不出现具体用例中，都使用PO中封装好的

**Comment by loveshanshan** [comment]
使用try catch, 暂时解决问题

**Comment by loveshanshan** [comment]
已找到解决办法，谢谢
