### ISSUE TITLE
测试报告生成后有部分被HtmlTestrunner遮挡

### ISSUE THREAD

**Issue by MarinPeng** [SeldomQA/seldom#50]
**
![1](https://user-images.githubusercontent.com/50908315/105669142-a0b57600-5f19-11eb-82e0-d8c0db7cd62f.png)
**
测试报告生成缺陷。期望修改
seldom version：1.9.0

**Comment by defnngj** [comment]
`version 1.10.0` 版本已经发布，并修复了这个问题。
