### ISSUE TITLE
执行脚手架提示'seldom' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by fungfungqaq** [SeldomQA/seldom#51]

**Comment by defnngj** [comment]
如果是windows 用户,

1. 检查seldom 是否安装成功

```shell
pip show seldom
```
如果提示`pip` 不是内部或外部命令，你需要配置python的环境变量

2. 如果可以看到seldom的安装信息，你需要在`Script`目录下查看是否有seldom可以执行文件。例如

```shell
C:\\python37\Script\seldom.exe
```
3.  如果没有seldom.exe文件，卸载seldom 重新安装。
```shell
> pip uninstall seldom
> pip install seldom
```
