### ISSUE TITLE
mail中的"skip用例"数量与result.html显示的不一致

### ISSUE THREAD

**Issue by Spycsh** [SeldomQA/seldom#59]
Email中收到显示skip用例数量为0

![https://raw.githubusercontent.com/Spycsh/Bugs/master/bug1.PNG](https://raw.githubusercontent.com/Spycsh/Bugs/master/bug1.PNG)

然而附件的result.html中chart和Overview能看到的skip用例数量为1

![https://raw.githubusercontent.com/Spycsh/Bugs/master/bug2.png](https://raw.githubusercontent.com/Spycsh/Bugs/master/bug2.png)

两个结果不一致.

**Comment by defnngj** [comment]
代码已合并！
