### ISSUE TITLE
截图不正确，无法看到断言失败时的截图

### ISSUE THREAD

**Issue by jingyuezijing** [SeldomQA/seldom#61]
用例结构如图：
def start(self):
 登录操作
def testcase(self):
这里是具体测试用例
def end(self):
退出登录操作

问题：
有用例执行失败时，查看测试报告的截图，都是注销后的操作截图，无法知道testcase执行过程中哪一步出了问题，导致用例失败

**Comment by defnngj** [comment]
要在start()/end() 写web操作步骤，如果失败了无法统计那一条用例失败，并且也无法截图。 你可以单独封装普通的方法，在case中调用。

**Comment by jingyuezijing** [comment]
> 要在start()/end() 写web操作步骤，如果失败了无法统计那一条用例失败，并且也无法截图。 你可以单独封装普通的方法，在case中调用。

感谢回复，那我自己截图的文件 要如何显示在测试报告中呢？有没有接口说明
