### ISSUE TITLE
selenium中的显示等待在seldom中如何调用？如：判断某个元素消失

### ISSUE THREAD

**Issue by jingyuezijing** [SeldomQA/seldom#62]
![image](https://user-images.githubusercontent.com/77383326/118753680-d3a8be80-b8a8-11eb-866f-4edbd124f460.png)
如下，selenium中的等待一个元素消失的方法，在seldom有接口吗？
ui.WebDriverWait(driver, timeout).until_not(EC.visibility_of_element_located((By.XPATH, locator)))

**Comment by defnngj** [comment]
等待元素可见，seldom 默认会判断元素是否可见，根据 timeout  超时时间。

```py
seldom.main(timeout=10)
```

等待元素消失，比如弹提示框之类，一定有固定的消失时间，直接 休眠即可。
```py
self.sleep(10)
```

如果不知道一个元素存在还是消失，可以获取元素进行判断。

```py
elem = get_elements(xpath="//div")
```

在seldom 中，不需要像你上面那样 等待元素显示或隐藏。

**Comment by defnngj** [comment]
等待元素可见，seldom 默认会判断元素是否可见，根据 timeout  超时时间。

```py
seldom.main(timeout=10)
```

等待元素消失，比如弹提示框之类，一定有固定的消失时间，直接 休眠即可。
```py
self.sleep(10)
```

如果不知道一个元素存在还是消失，可以获取元素进行判断。

```py
elem = get_elements(xpath="//div")
```

在seldom 中，不需要像你上面那样 等待元素显示或隐藏。

**Comment by jingyuezijing** [comment]
if elem.isdisplay():
    步骤1
步骤2

不确定某一个元素是否存在，所以用if判断下，若if里的elem找不到。则到步骤2时，元素都获取不到了。是什么问题？

**Comment by sobbingchild** [comment]
希望作者能够提供或者封装下显示等待方法，当用例过多或者需要等待的用例过多，添加太多sleep影响运行时间较大，且seldom.main中有时候并没有在等待，比如应为操作过快提示stale element reference: element is not attached to the page document。必须强制等待

**Comment by defnngj** [comment]
`seldom==3.9.1` 版本增加 `is_visible()`方法。

* 用法

```py
import seldom
from seldom import Steps


class BingTest(seldom.TestCase):
    """Bing search test case"""

    def test_case(self):
        """a simple test case """
        self.open("https://cn.bing.com")
        self.is_visible(timeout=10, xpath="//*[@id='xxx']")
        
```
