### ISSUE TITLE
poium 中，为什么Elements 没有timeout参数，而Element有？

### ISSUE THREAD

**Issue by jingyuezijing** [SeldomQA/seldom#67]
![image](https://user-images.githubusercontent.com/77383326/123948788-64a8a480-d9d4-11eb-9983-091ed5be4689.png)
![image](https://user-images.githubusercontent.com/77383326/123948842-738f5700-d9d4-11eb-8e9a-d44ec1860629.png)

poium 中，为什么Elements 没有timeout参数，而Element有？

**Comment by defnngj** [comment]
`Eelment` 用于获取单个元素，如果获取不到可以通过`timeout` 设置等待时间（次数）。

`Eelments` 用户获取一组元素，可以为空、1个或多个，本来结果不确定性就很大，所以没加！

举个例子： 

你去幼儿园接（1个）小孩，接不到肯定要等一等，可能孩子还没放学。

火车发车一般是准点的，管你是0个乘客，1个乘客，还是100个乘客。 等待的判断条件是什么？ 0乘客就等？ 不够100个乘客就等？ 所以，等待的条件就不确定了。
