### ISSUE TITLE
列表索引超出范围

### ISSUE THREAD

**Issue by admin8548** [SeldomQA/seldom#71]
接口请求
get方式，seldom报错，requests没有报错
![屏幕截图 2021-09-07 225935](https://user-images.githubusercontent.com/84054856/132367109-b14ca6be-4be5-4400-a3e8-dc2403123e61.png)

这种该如何解决

**Comment by defnngj** [comment]
@admin8548  已修复了。

`url=` 参数不需要指定。

```python

    def test_03(self):
        self.get("http://127.0.0.1:8810/api/v2/ideas/subjects/185/meta/")

```

修复之后，可以指定，也可以不指定。
