### ISSUE TITLE
多人发送邮件失败

### ISSUE THREAD

**Issue by Jixiang-style** [SeldomQA/seldom#72]
![image](https://user-images.githubusercontent.com/68281584/132650312-9369826d-1433-4799-a0e2-478f1c01831c.png)
to所跟对象为列表时，发送邮件失败
![image](https://user-images.githubusercontent.com/68281584/132650373-333f18d2-da08-4227-9286-ee63bace5e46.png)

**Comment by defnngj** [comment]
以列表方式支持多个邮箱接收

```python
if __name__ == '__main__':
    seldom.main(browser="ff")
    smtp = SMTP(user="send@qq.com", password="123", host="smtp.qq.com")
    smtp.sender(to=["aa@qq.com", "bb@126.com"， "cc@gmail.com"], subject='Email title')

```
