### ISSUE TITLE
断言-->能否支持检查在当前给用户显示的页面上是否没有出现指定的文本

### ISSUE THREAD

**Issue by sobbingchild** [SeldomQA/seldom#75]
一、现支持的断言方法
使用方法
断言标题是否等于"title"
self.assertTitle("title")
 断言标题是否包含"title"
self.assertInTitle("title")
 断言URL是否等于
self.assertUrl("url")
 断言URL是否包含
self.assertInUrl("url")
断言页面是否存在“text”
self.assertText("text")
 断言警告是否存在"text" 提示信息
self.assertAlertText("text")
断言元素是否存在
self.assertElement(css="#kw")

断言元素是否不存在
self.assertNotElement(css="#kwasdfasdfa")
二、使用的场景及希望支持的断言方法
设计用例的时候，一个输入框输入部分存在及不存在于数据库ip的主机，进行搜索
即断言的时候希望要检测是否存在文本及不存在的文本，目前assertText可满足大部分场景，但现场景需要检查在当前给用户显示的页面上是否没有出现指定的文本，类似selenium中的assertTextNotPresent（）方法

**Comment by sobbingchild** [comment]
![image](https://user-images.githubusercontent.com/66291315/142559396-da4c5a4f-0bca-4015-b229-a8bda3a2b450.png)
修改case.py文件后调用该方法，界面确认不存在该文件即TEST_IP。

**Comment by defnngj** [comment]
`seldom >=2.3.3` 版本已经支持

```py
self.assertNotText()
```
