### ISSUE TITLE
请问有谁遇到过 这种问题：在用例中使用全路径引用模块，使用命令行运行python run.py时提示用例中引用的模块不存在，用pycharm可以运行。

### ISSUE THREAD

**Issue by Gary-CHAO1** [SeldomQA/seldom#89]
如题，提示引用的模块不存在

**Comment by footmanqq** [comment]
![image](https://user-images.githubusercontent.com/32947488/158010800-cfc50d13-7aa5-41f0-b316-84cbd8a7d475.png)
我猜测你选择执行路径有问题，pycharm是会自动加上根目录的

**Comment by Gary-CHAO1** [comment]
是的，感谢
