### ISSUE TITLE
虫师，请教一个关于你的pyse框架代码的问题

### ISSUE THREAD

**Issue by eastchenyd** [SeldomQA/seldom#9]
def assertTitle(self, title, second=3):
        '''
        Asserts whether the current title is in line with expectations.
        The default is 3 seconds.
        Usage:
        driver.assertTitle("title")
        '''
        if title == None:
            raise NameError("'title' can't be empty.")
        for s in range(second):
            try:
                self.assertIn(title, self.driver.get_title())
                break
            except AssertionError:
                sleep(1)
        else:
            self.assertIn(title, self.driver.get_title())

上面的else语句是否必要，for循环迭代完为空才执行else语句，但是else语句的执行内容跟for语句里的执行内容是一样的，我的理解再次执行还是没找到，是不是多余了？

**Comment by defnngj** [comment]
for  循环中对assertIn()断言异常进行了捕捉了，所以，整个循环结束，就算每次都断言失败也不会抛异常。else 当整个循环执行 break 时会被执行。 
其实，else 部分应该我自己定义异常错误，告诉用户断言失败，但是，unittest 的异常提示比自定义的优雅。所以再次调用 assertIn() 使异常抛出。
----
这样设计有点不太优雅，但实现的功能是对的！
