### ISSUE TITLE
seldom平台化支持,执行后拿不到结果或报告路径，不知道正确对应的报告是哪个

### ISSUE THREAD

**Issue by footmanqq** [SeldomQA/seldom#90]
已查阅[seldom](https://github.com/SeldomQA/seldom)/[docs](https://github.com/SeldomQA/seldom/tree/master/docs)/platform.md文件内容。且run方法都没有提供返回值告知result或报告路径。麻烦大佬确认下这块何时能够在框架层面支持上，或指明下如何灵活处理的方式。感谢！！！

**Comment by footmanqq** [comment]
![image](https://user-images.githubusercontent.com/32947488/158545559-af4f1c99-24ed-4052-ba05-5bd42db4b59a.png)
查阅源码，可以配置BrowserConfig.REPORT_PATH 报告路径。或者拿到xml文件结果。

**Comment by footmanqq** [comment]
实践了下，以上方式不行，  会抛异常  with(open(report_path, 'wb')) as fp:
OSError: [Errno 22] Invalid argument:

**Comment by footmanqq** [comment]
报告路径可以如此配置，日志log路径配置无效

**Comment by defnngj** [comment]
你没理解这个功能。调用相关api 只会返 __回当前项目中的用例信息__。 以及__去接收要执行的用例信息__。

例如：

你之前去订酒店，只能跑到某个具体的酒店的前台，选择预定。

现在，你可以打电话，服务人员把所有酒店信息给你（返回当前项目中的用例信息），你可以任意的选择 酒店预定(去接收要执行的用例信息) 

相关项目，虽然没完全实现，看截图应该能明白。
https://github.com/SeldomQA/seldom-platform 

技术交流群(QQ)：948994709
