### ISSUE TITLE
执行目录下的所有.py文件用例失败，只执行了目录下的第一个文件

### ISSUE THREAD

**Issue by gitgogo** [SeldomQA/seldom#91]
目录文件：
<img width="724" alt="image" src="https://user-images.githubusercontent.com/15121312/159514589-07e37197-dca2-4941-b1e4-3d5395a75463.png">

报告结果：
<img width="838" alt="image" src="https://user-images.githubusercontent.com/15121312/159514484-1a48f126-9dce-4f43-83df-f62ecc3e5600.png">

**Comment by defnngj** [comment]
seldom 全局控制浏览器的开启和关闭，不需要每个用例做浏览器的开启和关闭处理。
