### ISSUE TITLE
请问有没有人遇到这个问题：在使用@file_data做数据驱动时，第二次运行时数据文件有变动，但是在执行时，数据取的时第一次的数据？

### ISSUE THREAD

**Issue by Gary-CHAO1** [SeldomQA/seldom#92]
如题，比如第一次生成的数据文件中有个数据A:1，第二次生成的数据文件中A的值变为2，但在使用@file_data取A的值还是1

**Comment by defnngj** [comment]
可否给出具体的例子 和 执行结果。 但从文字描述很难确定是seldom 的问题。

**Comment by Gary-CHAO1** [comment]
如图
![fail](https://user-images.githubusercontent.com/101296901/160032864-30c2ac13-975f-4929-bf66-4baebaab88db.png)

**Comment by defnngj** [comment]
`数据文件` 在用例运行之前会被加载一次；在用例运行过程当中修改`数据文件` 是不生效的。如果数据文件中的数据在运行用例过程当中要被多次修改 并用到别的用例。请不要用数据文件，可以定义全局变量。 @Gary-CHAO1
