### ISSUE TITLE
【功能】添加调试单个test_case功能

### ISSUE THREAD

**Issue by lazysang** [SeldomQA/seldom#94]
现在调试起来的最小单位为单个py文件，但是一个py文件有好几个case，我想单独调试却办不到。
我看了#84这个问题，里面的解决方法是在命令行单独调用，我试过有问题，我在case外有其他操作好像没有整进去。

所以想新增一个单独调试单个test_case功能

我试着改了一下代码，大概就是下面这样，代码质量可能不好，但是大概就是这个思路

runner.py文件
``` python
class TestMain(object):
    def __init__(self, case_name=None.......
    self.case_name = case_name
    ......
        # ----- Global open browser -----
        self.open_browser()
        if self.case_name is not None:
                self.TestSuits = seldomTestLoader.loadTestsFromName(self.case_name)
        elif self.path is None:
        ......
```

**Comment by footmanqq** [comment]
目前就用 ide(vscode\pycharm)支持unittest 测试，进行单个case调试

**Comment by lazysang** [comment]
seldom.main()里面有传参数，seldom.main()前面也有特殊操作，所以使用提供的那些方法（比如vscode的unittest）都不能调试单个用例，所以才产生了这个需求，希望在main()里面可以添加单个case，应为其他方式都不行。

**Comment by defnngj** [comment]
@lazysang   非常感谢你的建议，代码已实现！ 

欢迎加QQ官方群：948994709 ，贡献更多好的想法。
