### ISSUE TITLE
api中如何获取cookie并延用到下个接口

### ISSUE THREAD

**Issue by liuyi1804** [SeldomQA/seldom#99]

**Comment by defnngj** [comment]
@liuyi1804 
通过 `Session ()` 可以记录用户的cookie ： 
参考文档：https://seldomqa.github.io/http/http.html#session%E4%BD%BF%E7%94%A8

**Comment by defnngj** [comment]
文档更新，新的地址：https://seldomqa.github.io/api-testing/more.html#session%E4%BD%BF%E7%94%A8
